# Generated by Django 2.2 on 2020-01-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200128_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
